server:
  port: 10010 #服务端口
spring:
  application:
    name: bnz-zuul #指定服务名
zuul:
  routes:
    bnz-commodity: #路由名称 通常是微服务名称
      path: /bnz-commodity/** # 这里是映射路径
      url: http://localhost:8090 # 映射路径对应的实际url地址
eureka:
  client:
    service-url: # EurekaServer地址
      defaultZone: http://127.0.0.1:10086/eureka
ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeout-in-milliseconds: 3000
