server:
  port: 8091
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/business?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
  application:
    name: bnz-commodity-desc
    main:
      allow-bean-definition-overriding: true #解决报错问题
mybatis:
  typeAliasesPackage: cn.bnz.dy.entity
  mapperLocations: classpath:mapper/*.xml

eureka:
  client:
    service-url: # EurekaServer地址
      defaultZone: http://127.0.0.1:10086/eureka